# Generated by Django 4.0 on 2021-12-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director_name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
